# Generated by Django 4.1.13 on 2026-05-30 05:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=50, unique=True)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_text', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='GameSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('last_played', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_consumable', models.BooleanField(default=False)),
                ('equippable_slot', models.CharField(blank=True, max_length=50, null=True)),
                ('strength_boost', models.IntegerField(default=0)),
                ('mana_boost', models.IntegerField(default=0)),
                ('weight', models.IntegerField(default=0)),
                ('defense_boost', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_hidden', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Quest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=50, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('reward', models.CharField(max_length=200)),
                ('note', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sound_volume', models.IntegerField(default=50)),
                ('text_speed', models.IntegerField(default=50)),
                ('auto_save', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StoryNode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('narrative_text', models.TextField()),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='modules.location')),
            ],
        ),
        migrations.CreateModel(
            name='SaveSlot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot_name', models.CharField(default='slot1', max_length=50)),
                ('save_name', models.CharField(max_length=100)),
                ('state_data', models.TextField(blank=True, null=True)),
                ('is_autosave', models.BooleanField(default=False)),
                ('saved_at', models.DateTimeField(auto_now_add=True)),
                ('saved_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modules.storynode')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saves', to='modules.gamesession')),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredient_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe_ing1', to='modules.item')),
                ('ingredient_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe_ing2', to='modules.item')),
                ('result_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe_result', to='modules.item')),
            ],
        ),
        migrations.CreateModel(
            name='PlayerStats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('health', models.IntegerField(default=100)),
                ('sanity', models.IntegerField(default=100)),
                ('reputation', models.IntegerField(default=0)),
                ('overheat', models.IntegerField(default=0)),
                ('status_ailments', models.JSONField(blank=True, default=dict)),
                ('elemental_resistances', models.JSONField(blank=True, default=dict)),
                ('mana', models.IntegerField(default=100)),
                ('defense', models.IntegerField(default=0)),
                ('level', models.IntegerField(default=1)),
                ('exp', models.IntegerField(default=0)),
                ('stat_points', models.IntegerField(default=0)),
                ('scrap', models.IntegerField(default=0)),
                ('base_strength', models.IntegerField(default=10)),
                ('base_intelligence', models.IntegerField(default=10)),
                ('base_dexterity', models.IntegerField(default=10)),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='modules.gamesession')),
            ],
        ),
        migrations.CreateModel(
            name='PlayerQuest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='active', max_length=20)),
                ('quest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modules.quest')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quests', to='modules.gamesession')),
            ],
        ),
        migrations.CreateModel(
            name='PlayerChoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chosen_at', models.DateTimeField(auto_now_add=True)),
                ('choice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modules.choice')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices_made', to='modules.gamesession')),
            ],
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modules.item')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to='modules.gamesession')),
            ],
        ),
        migrations.AddField(
            model_name='gamesession',
            name='current_location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='active_sessions', to='modules.location'),
        ),
        migrations.AddField(
            model_name='gamesession',
            name='current_node',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='active_sessions', to='modules.storynode'),
        ),
        migrations.AddField(
            model_name='gamesession',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='GameLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='modules.gamesession')),
            ],
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot', models.CharField(max_length=50)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modules.item')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipment', to='modules.gamesession')),
            ],
        ),
        migrations.CreateModel(
            name='Consequence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('effect_type', models.CharField(choices=[('health', 'Health'), ('sanity', 'Sanity'), ('reputation', 'Reputation'), ('item', 'Item'), ('flag', 'Flag')], max_length=20)),
                ('reference_id', models.IntegerField(blank=True, null=True)),
                ('effect_value', models.IntegerField()),
                ('choice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consequences', to='modules.choice')),
            ],
        ),
        migrations.AddField(
            model_name='choice',
            name='next_node',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_choices', to='modules.storynode'),
        ),
        migrations.AddField(
            model_name='choice',
            name='node',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='modules.storynode'),
        ),
    ]
